server.port=5454

# DB specific properties
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_multivendor
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# ORM properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Razorpay
razorpay.api.key=${RAZORPAY_API_KEY}
razorpay.api.secret=${RAZORPAY_API_SECRET}

# Stripe
stripe.api.key=${STRIPE_API_KEY}

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.devtools.livereload.enabled=true

# AI
gemini.api.key=${GEMINI_API_KEY}